import os
env_options={
  "CC":"gcc",
  "CXX":"g++",
  "AR":"ar",
  "CCFLAGS":[],
  "ENV":{"PATH":os.environ["PATH"]}
}
print env_options['ENV']
env=Environment(**env_options)
env['CCFLAGS'].extend(['-Iinclude'])
env['CCFLAGS'].extend(['-std=c++11'])
env.Program('prog',[Glob('*.c'),Glob('*.cpp')])
