Import('env')
target="prog"
#env['CCFLAGS'].append('-finstrument-functions')
#env['CCFLAGS'].append('-g')
env['CCFLAGS'].append('-Wno-unused-function')
env['CCFLAGS'].append('-Wno-unused-variable')
prog=env.Program(target,[Glob('*.c'),Glob('*.cpp')],CPPPATH=['include'],LIBS=['pthread','rt'])

