import os
Import('env')
target=os.path.basename(os.getcwd())
testTarget=target+'Test'
env.Library(target,[Glob('*.c'),Glob('../utils/*.c')])
env.Program(testTarget,[Glob('*.c'),Glob('../utils/*.c'),Glob('test/*.c')])
env.Install('../../bin', testTarget)
